#!/usr/bin/env python3
"""
Comprehensive test to verify the double index bug is completely fixed.
Tests both the auto-fix and the cleanup functions.
"""

from app.chains.template_structure_generator import TemplateStructureGenerator


def test_comprehensive_double_index_fix():
    """Test that simulates real-world scenarios with potential double indices"""

    generator = TemplateStructureGenerator(db_session=None, embedding_model=None)

    print("=" * 80)
    print("COMPREHENSIVE TEST: Real-world scenario with nested structures")
    print("=" * 80)

    # Simulate the kind of data structure that might cause the original error
    source_paths = [
        "thèmes[x]titre",
        "thèmes[x]médias_référencés[y]nom",
        "thèmes[x]médias_référencés[y]usage_suggéré",
        "thèmes[x]médias_référencés[y]description",
    ]

    # This represents mappings that could have been generated by LLM
    # with potential conflicts
    mappings = {
        "thèmes[x]titre": 'layouts/vertical_column/container["items"][x]layouts/vertical_column/item["title"]text/titre["text"]',
        "thèmes[x]médias_référencés[y]nom": 'layouts/vertical_column/container["items"][x]layouts/vertical_column/item["content"]layouts/tree_left_right/container["items"][y]conceptual/concept["title"]',
        "thèmes[x]médias_référencés[y]usage_suggéré": 'layouts/vertical_column/container["items"][x]layouts/vertical_column/item["content"]layouts/tree_left_right/container["items"][y]conceptual/concept["description"]',
        "thèmes[x]médias_référencés[y]description": 'layouts/vertical_column/container["items"][x]layouts/vertical_column/item["content"]layouts/tree_left_right/container["items"][y]text/description["text"]',
    }

    print("\n❌ MAPPINGS INITIAUX:")
    for src, dest in mappings.items():
        print(f'  "{src}":')
        print(f'    {dest}')

    # Check for conflicts
    errors_before = generator._validate_destination_mappings(mappings)
    print(f"\n📊 Conflits détectés AVANT: {len(errors_before)}")
    if errors_before:
        for err in errors_before[:2]:  # Show first 2 errors
            print(f"  {err[:150]}...")

    # Apply auto-fix
    print("\n🔧 Application de la correction automatique...")
    fixed_mappings = generator._auto_fix_overlaps(mappings, source_paths)

    print("\n✅ MAPPINGS CORRIGÉS:")
    for src, dest in fixed_mappings.items():
        print(f'  "{src}":')
        print(f'    {dest}')

    # Validate no double indices
    has_double_index = False
    for src, dest in fixed_mappings.items():
        segments = generator._parse_destination_path(dest)
        for i in range(len(segments) - 1):
            if segments[i]["type"] == "index" and segments[i+1]["type"] == "index":
                print(f"\n❌ DOUBLE INDEX TROUVÉ dans '{src}':")
                print(f"    {segments[i]} -> {segments[i+1]}")
                has_double_index = True

    # Validate no conflicts
    errors_after = generator._validate_destination_mappings(fixed_mappings)
    print(f"\n📊 Conflits détectés APRÈS: {len(errors_after)}")

    # Final result
    print("\n" + "=" * 80)
    if not has_double_index and len(errors_after) == 0:
        print("✅✅✅ SUCCÈS COMPLET! Aucun double index, aucun conflit.")
    else:
        print("❌ ÉCHEC: Des problèmes persistent.")
        if has_double_index:
            print("  - Double indices détectés")
        if errors_after:
            print(f"  - {len(errors_after)} conflit(s) restant(s)")
    print("=" * 80)

    # Test insertion into structure
    print("\n🧪 Test d'insertion dans la structure...")
    test_data = {
        "thèmes": [
            {
                "titre": "Test Theme",
                "médias_référencés": [
                    {
                        "nom": "Media 1",
                        "usage_suggéré": "Usage 1",
                        "description": "Desc 1",
                    }
                ],
            }
        ]
    }

    try:
        # Get paths with indices
        json_paths = generator._extract_all_json_paths(test_data, include_indices=True)

        # Try building final JSON
        result = generator._build_final_json(
            source_json=test_data,
            destination_mappings=fixed_mappings,
            json_paths_with_indices=json_paths,
        )

        print("✅ Insertion réussie!")
        print(f"Structure générée avec {len(str(result))} caractères")

    except Exception as e:
        print(f"❌ Insertion échouée: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    test_comprehensive_double_index_fix()
